name:                handson-haskell
version:             0.1.0.0
github:              "jtonic/handson-haskell"
license:             BSD3
author:              "Antonel-Ernest Pazargic"
maintainer:          "antonel.pazargic@gmail.com"
copyright:           "2020 Antonel-Ernest Pazargic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Web

description:         Please see the README on GitHub at <https://github.com/githubuser/handson-haskell#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wempty-enumerations
- -XTypeApplications
- -Wincomplete-patterns
- -XGADTs
- -XLambdaCase
- -XNegativeLiterals
- -XFlexibleContexts
- -Wno-missing-signatures
- -Wno-unused-local-binds
- -Wno-type-defaults

dependencies:
- base >= 4.7 && < 5
- text
- exceptions
- text-show
- HsYAML
- lens
- extra
- deepseq
- parallel
- bytestring
- random
- containers
- warp
- wai
- yesod
- http-types
- aeson
- conferer
- conferer-warp

library:
  source-dirs: src

executables:
  handson-haskell-exe:
    source-dirs:         app
    main:                Main.hs
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-haskell

tests:
  handson-haskell-test:
    source-dirs:         test
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-haskell
    - QuickCheck


