on: [push]
name: build
jobs:
  haskell-build:
    name: Handson-haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
