on: [push]
name: build
jobs:
  haskell-build:
    name: Handson-haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10'
          cabal-version: '3'
          enable-stack: true
          stack-version: '2.5'
      - run: stack test --fast
