on: [push]
name: build
jobs:
  haskell-build:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack --version
