# Haskel github action
# https://github.com/actions/setup-haskell

on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8.4']
        cabal: ['latest']
        os: [ubuntu-latest, macOS-latest]
        # exclude:
        #   # GHC 8.8+ only works with cabal v3+
        #   - ghc: 8.8.3
        #     cabal: 2.4.1.0
    name: Haskell GHC ${{ matrix.ghc }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
          stack-version: 'latest'
      - run: cabal build
